# Titanic Survival Prediction

## Objective
The objective of this project is to analyze the Titanic dataset, identify factors affecting survival, and build a machine learning model to predict passenger survival.

In [2]:
import pandas as pd
df=pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
age_median=df["Age"].median()
print(age_median)

28.0

In [8]:
df['Age_Median']=df["Age"].fillna(age_median)

In [9]:
df[df["Age"].isnull()][["Age","Age_Median"]].head(10)

    Age  Age_Median
5   NaN        28.0
17  NaN        28.0
19  NaN        28.0
26  NaN        28.0
28  NaN        28.0
29  NaN        28.0
31  NaN        28.0
32  NaN        28.0
36  NaN        28.0
42  NaN        28.0

In [10]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [11]:
df["Age"].describe()

count    891.000000
mean      29.361582
std       13.019697
min        0.420000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Age_Median       0
dtype: int64

In [13]:
df.drop("Cabin", axis=1, inplace=True)

In [14]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
Age_Median     0
dtype: int64

In [15]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [16]:
df["Embarked"].mode()

0    S
Name: Embarked, dtype: str

In [17]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [18]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Age_Median     0
dtype: int64

In [19]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [20]:
df.drop(
    ["PassengerId", "Name", "Ticket"],
    axis=1,
    inplace=True
)

In [21]:
pd.crosstab(df["Sex"], df["Survived"])

Survived    0    1
Sex
female     81  233
male      468  109

In [22]:
pd.crosstab(df["Pclass"], df["Survived"])

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

In [23]:
df.groupby("Survived")["Fare"].mean()

Survived
0    22.117887
1    48.395408
Name: Fare, dtype: float64

In [24]:
df["Sex"] = df["Sex"].map({
    "male": 0,
    "female": 1
})
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked  Age_Median
0         0       3    0  22.0      1      0   7.2500        S        22.0
1         1       1    1  38.0      1      0  71.2833        C        38.0
2         1       3    1  26.0      0      0   7.9250        S        26.0
3         1       1    1  35.0      1      0  53.1000        S        35.0
4         0       3    0  35.0      0      0   8.0500        S        35.0

In [25]:
df = pd.get_dummies(
    df,
    columns=["Embarked"],
    drop_first=True
)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Age_Median,Embarked_Q,Embarked_S
0,0,3,0,22.0,1,0,7.2500,22.0,False,True
1,1,1,1,38.0,1,0,71.2833,38.0,False,False
2,1,3,1,26.0,0,0,7.9250,26.0,False,True
3,1,1,1,35.0,1,0,53.1000,35.0,False,True
4,0,3,0,35.0,0,0,8.0500,35.0,False,True

## Feature Engineering

Categorical variables were converted into numerical form for machine learning.

In [26]:
X = df[
    [
        "Pclass",
        "Sex",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "Embarked_Q",
        "Embarked_S"
    ]
]

In [27]:
y = df["Survived"]

In [28]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Age_Median', 'Embarked_Q', 'Embarked_S'],
      dtype='str')

In [29]:
df.drop("Age_Median", axis=1, inplace=True)

In [30]:
print(X.shape)
print(y.shape)

(891, 8)
(891,)

In [31]:
X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0       3    0  22.0      1      0   7.2500       False        True
1       1    1  38.0      1      0  71.2833       False       False
2       3    1  26.0      0      0   7.9250       False        True
3       1    1  35.0      1      0  53.1000       False        True
4       3    0  35.0      0      0   8.0500       False        True

In [32]:
X = X.astype(int)

In [33]:
X

     Pclass  Sex  Age  SibSp  Parch  Fare  Embarked_Q  Embarked_S
0         3    0   22      1      0     7           0           1
1         1    1   38      1      0    71           0           0
2         3    1   26      0      0     7           0           1
3         1    1   35      1      0    53           0           1
4         3    0   35      0      0     8           0           1
..      ...  ...  ...    ...    ...   ...         ...         ...
886       2    0   27      0      0    13           0           1
887       1    1   19      0      0    30           0           1
888       3    1   28      1      2    23           0           1
889       1    0   26      0      0    30           0           0
890       3    0   32      0      0     7           1           0

[891 rows x 8 columns]

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## Train-Test Split

In [36]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

## Logistic Regression Model

In [37]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [38]:
y_pred = model.predict(X_test)

## Predictions

In [39]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.8100558659217877

## Model Evaluation

The model achieved approximately 81% accuracy.

# Conclusion

Key Findings:

- Female passengers had significantly higher survival rates.
- First-class passengers had better survival outcomes.
- Higher fares were associated with higher survival chances.
- Overall survival rate was 38.38%.
- Logistic Regression achieved approximately 81% accuracy.

This project demonstrates data cleaning, exploratory data analysis, machine learning, and dashboard development using the Titanic dataset.